# Generated by Django 3.2.4 on 2021-06-22 02:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('active', models.BooleanField(default=True)),
                ('add_date', models.DateTimeField(default=datetime.date(2021, 6, 22))),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default='Active')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 0, 0))),
                ('receiver_subs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='referallApp.subscriber', verbose_name='Receiver')),
                ('sender_subs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='referallApp.subscriber', verbose_name='Sender')),
            ],
        ),
    ]
